// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// spikeCenter
IntegerVector spikeCenter(NumericVector signal, int window, double threshold, double spikeAmp, int timeframe);
RcppExport SEXP _spiker_spikeCenter(SEXP signalSEXP, SEXP windowSEXP, SEXP thresholdSEXP, SEXP spikeAmpSEXP, SEXP timeframeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type signal(signalSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type spikeAmp(spikeAmpSEXP);
    Rcpp::traits::input_parameter< int >::type timeframe(timeframeSEXP);
    rcpp_result_gen = Rcpp::wrap(spikeCenter(signal, window, threshold, spikeAmp, timeframe));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spiker_spikeCenter", (DL_FUNC) &_spiker_spikeCenter, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_spiker(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
