# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_center_spike_filter <- function(signal, parameter_list, dates_idx = NULL) {
    .Call('_spiker_C_center_spike_filter', PACKAGE = 'spiker', signal, parameter_list, dates_idx)
}

C_lagging_spike_filter <- function(signal, parameter_list) {
    .Call('_spiker_C_lagging_spike_filter', PACKAGE = 'spiker', signal, parameter_list)
}

