# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

spike_center <- function(signal, window, threshold, spikeAmp, timeframe, dates_idx = NULL) {
    .Call(`_spiker_spike_center`, signal, window, threshold, spikeAmp, timeframe, dates_idx)
}

